

\chapter{DESCRIPTIVE STATISTICS TABLES}

\realSingleSpace
```{r}


```
\doublespacing

{{< pagebreak >}}

\realSingleSpace
```{r}


```
\doublespacing

{{< pagebreak >}}

\realSingleSpace
```{r}
#| label: tbl-vars
#| tbl-cap: All Variables and Their Sources
#| tbl-pos: H
#| message: false

# tbl_vars <- tribble(
#   ~var, ~source, ~time_measured,
#   "Transit Stop Within 0.5 Miles", "SHS Transit Map XL", "Spring 2021",
#   "Retention Rate", "IPEDS", "Fall 2021 - Fall 2022",
#   "Locale", "IPEDS", "Fall 2021",
#   "Public or Private", "IPEDS", "Fall 2021",
#   "Region", "IPEDS", "Fall 2021",
#   "2-Year or 4-Year", "IPEDS", "Fall 2021",
#   "Open Access or Not", "IPEDS", "Fall 2021",
#   "Cohort % Women", "IPEDS", "Fall 2021",
#   "Cohort % White", "IPEDS", "Fall 2021",
#   "Undergraduate % Pell Grant", "IPEDS", "Fall 2021",
#   "Undegraduate % On-Campus", "IPEDS", "Fall 2021",
#   "Student to Faculty Ratio", "IPEDS", "Fall 2021",
#   "Spending on Instruction", "IPEDS", "Fall 2021",
#   "Spending on Student Services", "IPEDS", "Fall 2021",
#   "Average Net Price", "IPEDS", "Fall 2021",
#   "County % Bachelors", "ACS", "Jan 2017 - Dec 2021",
#   "County % Poverty", "ACS", "Jan 2017 - Dec 2021",
#   "County % No Automobile", "ACS", "Jan 2017 - Dec 2021",
#   "County Pop. Sq Mile", "ACS", "Jan 2017 - Dec 2021",
#   "County % Commute Using Transit", "ACS", "Jan 2017 - Dec 2021"
# )
# 
# kable(tbl_vars,
#       col.names = c("Variable", "Source", "Time Measured"),
#       format = "latex",
#       booktabs = TRUE,
#       digits = 2,
#       escape = TRUE,
#       linesep = "",
#       align = c("l", "l", "l")) |>
#   kable_styling(full_width = TRUE) |>
#   column_spec(1, width = "3in") |>  # Adjust width as needed
#   row_spec(0, align = "l")
```
\doublespacing


\chapter{DIAGNOSTIC DETAILS}


\realSingleSpace
```{r}
#| label: tbl-ps-bal-full
#| tbl-cap: Propensity Score Balance Table (Full)
#| tbl-pos: H
#| message: false

# kable(tbl_ps_bal_full,
#       col.names = c("Variable", "Std. Mean Diff.", "Balanced at <0.05"),
#       format = "latex",
#       booktabs = TRUE,
#       digits = 2,
#       escape = TRUE,
#       linesep = "",
#       align = c("l", "r", "r", "r")) |>
#   kable_styling(full_width = TRUE) |>
#   column_spec(1, width = "3in") |>  # Adjust width as needed
#   row_spec(0, align = "l")

```
\doublespacing

<!--

\chapter{R CODE}

\realSingleSpace
\small

# R Session Info

```{r}
#load("analysis/session-info.Rdata")

#print(r_ver)
#print(pack_ver)
```

{{< pagebreak >}}

# Download IPEDS Data

```{r}
#| echo: true
#| eval: false
# #| file: analysis/00-IPEDtaS.R
```

{{< pagebreak >}}

# Data Cleaning & Preparation

```{r}
#| echo: true
#| eval: false
# #| file: analysis/01-rtr-data.R
```

{{< pagebreak >}}

# Descriptive Data Visualizations

```{r}
#| echo: true
#| eval: false
# #| file: analysis/02-rtr-descriptives.R
```

{{< pagebreak >}}

# Regression Replication Analysis

```{r}
#| echo: true
#| eval: false
# #| file: analysis/03-rtr-regression.R
```

{{< pagebreak >}}

# Quasi-Experimental Analysis

```{r}
#| echo: true
#| eval: false
# #| file: analysis/04-rtr-quasi.R
```
\normalsize
\doublespacing

{{< pagebreak >}}

```{=latex}
%% h/t https://tex.stackexchange.com/questions/440046/title-of-subsection-on-included-multi-page-pdf

%\includepdf[width=\paperwidth,pages={1},trim={0in 0.5in 0in 2.5in},clip,
%pagecommand={\chapter{IRB EXEMPT DETERMINATION}},offset={0mm 0in}]{analysis/figures/irb-exempt.pdf}

%\includepdf[width=\paperwidth,pages={2-3},trim={0in 0in 0in 0.25in},clip,
%pagecommand={},offset={0mm 0in}]{analysis/figures/irb-exempt.pdf}
```

-->
